[METADATA]
modified = 2026-02-14T20:00:00Z
expires = 2027-02-14T20:00:00Z

[[ACCOUNTS]]
address = "rhx7TS94iyuEn5Nhs7MrzfnGscvoz2Dxgf"
description = "Official Issuer for ALH Token"

[[CURRENCIES]]
code = "ALH"
issuer = "rhx7TS94iyuEn5Nhs7MrzfnGscvoz2Dxgf"
display_precision = 2